services:
    agentsib_crontab.manager.default:
        class: 'AgentSIB\CrontabBundle\Doctrine\CrontabManager'
        arguments:
            - '@agentsib_crontab.command_parser'
            - '@agentsib_crontab.entity_manager'
            - '@event_dispatcher'
            - '%agentsib_crontab.cronjob_class%'
            - '%agentsib_crontab.logs_path%'
        public: false

    agentsib_crontab.entity_manager:
        class: 'Doctrine\ORM\EntityManager'
        arguments: ['%agentsib_crontab.model_manager_name%']
